import assert from "node:assert";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";

import {
  buildWithdrawalCredentials,
  computeDepositDataRoot,
  computeDomain,
  DepositDataType,
  DOMAIN_DEPOSIT,
  fromHex,
  generateDepositData,
  generateValidatorKeys,
  hex,
  networks,
  ONE_ETH_GWEI,
  verifyDepositData,
  ZERO_HASH,
} from "../../src/core.ts";
import type { DepositData } from "../../src/types.ts";

const TEST_MNEMONIC =
  "test test test test test test test test test test test junk";
const TEST_PASSWORD = "TestPassword123";

const domainFor = (chain: keyof typeof networks) =>
  computeDomain(DOMAIN_DEPOSIT, networks[chain].forkVersion, ZERO_HASH);

// Real deposit generated by this tool for hoodi and accepted by the deposit
// contract; pins domain, fork version, SSZ roots, and BLS against known data.
const GOLDEN_HOODI: DepositData = {
  pubkey:
    "b3d60e3322ae02501827ec82b79b4447d37dfe3a41398a0053f23d495c8634993ce8966feaf5f93bed607def4bd9dd29",
  withdrawal_credentials:
    "0200000000000000000000003e5f38ff6686fb8363df1c9a6d68ca61c99a11da",
  amount: "32000000000",
  signature:
    "b094f6c1852596864e4e09dc0dc5f85395399fe2a016518b7e8c2a48297ffefe0ae6a2f22026462363f171d5779f9e4f12005c7842195fe430cd21b20f8c8893d407fca1ac7b37bce66425dba471d0e83b43182c1ad69d923170f7aab2c923a0",
  deposit_message_root:
    "b690134ca3fa749575e91c2959e59388961a639162a8e9aeaee28c2e303655ed",
  deposit_data_root:
    "c480aa78d30175540ae91542870dafb3d6afbb40961ae8ef1c72eb1518ba06ab",
  network_name: "hoodi",
  deposit_cli_version: "depositor-cli",
  fork_version: "10000910",
};

describe("Spec compliance", () => {
  let TEST_DIR: string;

  before(async () => {
    TEST_DIR = await mkdtemp(join(tmpdir(), "depositor-spec-"));
  });

  after(async () => {
    await rm(TEST_DIR, { recursive: true, force: true });
  });

  describe("Golden vector (hoodi)", () => {
    it("verifies a known on-chain deposit", async () => {
      const isValid = await verifyDepositData(GOLDEN_HOODI, domainFor("hoodi"));
      assert.strictEqual(isValid, true);
    });

    it("rejects the same deposit under the mainnet domain", async () => {
      // Roots match (domain-independent), so this exercises the BLS branch
      const isValid = await verifyDepositData(
        GOLDEN_HOODI,
        domainFor("mainnet")
      );
      assert.strictEqual(isValid, false);
    });

    it("matches manual merkleization of the deposit data root", () => {
      const root = computeDepositDataRoot(
        "0x" + GOLDEN_HOODI.pubkey,
        "0x" + GOLDEN_HOODI.withdrawal_credentials,
        "0x" + GOLDEN_HOODI.signature,
        32_000_000_000n
      );
      assert.strictEqual(root.slice(2), GOLDEN_HOODI.deposit_data_root);
    });
  });

  describe("SSZ roots", () => {
    it("computeDepositDataRoot matches ssz.DepositData.hashTreeRoot for fresh data", async () => {
      const { signing, pubkey } = await generateValidatorKeys(
        TEST_MNEMONIC,
        0,
        TEST_PASSWORD,
        TEST_DIR
      );
      const wc = buildWithdrawalCredentials(
        1,
        pubkey,
        "0x1234567890123456789012345678901234567890"
      );
      const deposit = await generateDepositData(
        pubkey,
        signing,
        wc,
        32 * ONE_ETH_GWEI,
        "hoodi"
      );

      const sszRoot = hex(
        DepositDataType.hashTreeRoot({
          pubkey,
          withdrawalCredentials: wc,
          amount: 32 * ONE_ETH_GWEI,
          signature: fromHex(deposit.signature),
        })
      );
      const manualRoot = computeDepositDataRoot(
        deposit.pubkey,
        deposit.withdrawal_credentials,
        deposit.signature,
        32_000_000_000n
      ).slice(2);

      assert.strictEqual(deposit.deposit_data_root, sszRoot);
      assert.strictEqual(manualRoot, sszRoot);
    });
  });

  describe("Deposit data format", () => {
    it("emits all fields of the official deposit_data format per network", async () => {
      const { signing, pubkey } = await generateValidatorKeys(
        TEST_MNEMONIC,
        0,
        TEST_PASSWORD,
        TEST_DIR
      );
      const wc = buildWithdrawalCredentials(0, pubkey);

      for (const chain of Object.keys(networks)) {
        const deposit = await generateDepositData(
          pubkey,
          signing,
          wc,
          32 * ONE_ETH_GWEI,
          chain
        );

        assert.strictEqual(deposit.pubkey.length, 96, "48-byte pubkey");
        assert.strictEqual(
          deposit.withdrawal_credentials.length,
          64,
          "32-byte withdrawal credentials"
        );
        assert.strictEqual(deposit.signature.length, 192, "96-byte signature");
        assert.strictEqual(deposit.deposit_message_root.length, 64);
        assert.strictEqual(deposit.deposit_data_root.length, 64);
        assert.strictEqual(deposit.network_name, chain);
        assert.strictEqual(
          deposit.fork_version,
          hex(networks[chain].forkVersion),
          `fork_version should match ${chain} genesis fork version`
        );
        assert.strictEqual(deposit.deposit_cli_version, "depositor-cli");

        const isValid = await verifyDepositData(deposit, domainFor(chain));
        assert.strictEqual(isValid, true, `${chain} deposit should verify`);
      }
    });

    it("accepts the 1 ETH minimum deposit amount", async () => {
      const { signing, pubkey } = await generateValidatorKeys(
        TEST_MNEMONIC,
        0,
        TEST_PASSWORD,
        TEST_DIR
      );
      const wc = buildWithdrawalCredentials(
        2,
        pubkey,
        "0x1234567890123456789012345678901234567890"
      );
      const deposit = await generateDepositData(
        pubkey,
        signing,
        wc,
        ONE_ETH_GWEI,
        "hoodi"
      );
      assert.strictEqual(deposit.amount, ONE_ETH_GWEI.toString());
      const isValid = await verifyDepositData(deposit, domainFor("hoodi"));
      assert.strictEqual(isValid, true);
    });

    it("accepts fractional ETH amounts", async () => {
      const { signing, pubkey } = await generateValidatorKeys(
        TEST_MNEMONIC,
        0,
        TEST_PASSWORD,
        TEST_DIR
      );
      const wc = buildWithdrawalCredentials(
        2,
        pubkey,
        "0x1234567890123456789012345678901234567890"
      );
      const amount = 1.5 * ONE_ETH_GWEI;
      const deposit = await generateDepositData(
        pubkey,
        signing,
        wc,
        amount,
        "hoodi"
      );
      assert.strictEqual(deposit.amount, "1500000000");

      const manualRoot = computeDepositDataRoot(
        deposit.pubkey,
        deposit.withdrawal_credentials,
        deposit.signature,
        deposit.amount
      ).slice(2);
      assert.strictEqual(manualRoot, deposit.deposit_data_root);

      const isValid = await verifyDepositData(deposit, domainFor("hoodi"));
      assert.strictEqual(isValid, true);
    });
  });

  describe("Withdrawal credentials", () => {
    it("builds type 2 (compounding, EIP-7251) credentials correctly", () => {
      const pubkey = new Uint8Array(48).fill(1);
      const addr = "0x1234567890123456789012345678901234567890";
      const result = buildWithdrawalCredentials(2, pubkey, addr);

      assert.strictEqual(result.length, 32);
      assert.strictEqual(result[0], 2);
      assert.strictEqual(
        hex(result),
        "0200000000000000000000001234567890123456789012345678901234567890"
      );
    });

    it("throws for type 2 without an address", () => {
      assert.throws(
        () => buildWithdrawalCredentials(2, new Uint8Array(48)),
        /--wc-address is required/
      );
    });
  });

  describe("Keystore (EIP-2335)", () => {
    it("writes a version 4 keystore with matching pubkey and path", async () => {
      const { pubkey, path, keystoreFile } = await generateValidatorKeys(
        TEST_MNEMONIC,
        3,
        TEST_PASSWORD,
        TEST_DIR
      );

      const keystore = JSON.parse(
        await readFile(join(TEST_DIR, keystoreFile), "utf8")
      );

      assert.strictEqual(keystore.version, 4);
      assert.strictEqual(keystore.path, "m/12381/3600/3/0/0");
      assert.strictEqual(path, "m/12381/3600/3/0/0");
      assert.strictEqual(keystore.pubkey, hex(pubkey));
      assert.ok(keystore.crypto.kdf, "kdf module should be present");
      assert.ok(keystore.crypto.checksum, "checksum module should be present");
      assert.ok(keystore.crypto.cipher, "cipher module should be present");
    });
  });
});
